### ISSUE TITLE
egmde login session fails to start on lightdm < 1.22

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/egmde-snap#2] opened 2019-04-16 14:06 UTC
Install the egmde snap:
```plain
snap install --edge --classic egmde
```
Logout & select "egmde" session on login

Expect: log in to egmde
Actual: return to greeter

**Comment by AlanGriffiths** [comment] 2019-04-16 14:33
This may well be connected to the way lightdm is set up: using sddm works.

**Comment by andybalaam** [comment] 2019-04-17 12:03
I see the same behaviour on my GPD Pocket 2.  Launching from lightdm, egmde sometimes logs in and sometimes I return to greeter (about half the time I think).  From a virtual console (Ctrl-Alt-F1) when i run `egmde` it seems to start correctly every time.

**Comment by AlanGriffiths** [comment] 2019-04-17 15:00
There were some similar "login sometimes works" issues logged with Unity8 last year:

- https://github.com/ubports/unity8-desktop-install-tools/issues/22
- https://github.com/ubports/unity8-desktop-install-tools/issues/29
- https://github.com/ubports/unity8-desktop-install-tools/issues/30
- https://github.com/ubports/unity8-desktop-install-tools/issues/36

I don't see anything inspiring in the comments though.

**Comment by AlanGriffiths** [comment] 2019-07-03 16:22
Seems to be easily reproduced with lightdm, neither gdm nor sddm show this problem.

**Comment by robert-ancell** [comment] 2019-07-03 21:24
I just tried the following on a 16.04 LTS VirtualBox VM:
1. Login normally
2. Install:
`$ snap install --edge --classic egmde`
3. Logout
4. Select egmde
5. Login

I see the egmde shell. Keeps working after each logout/login.

Can you attach the logs from /var/log/lightdm when this fails?

**Comment by AlanGriffiths** [comment] 2019-07-03 22:19
Thanks @robert-ancell, I'll do that in my morning. I know andybalaam was using MATE, and the test system I used is 18.04LTS based.

**Comment by AlanGriffiths** [comment] 2019-07-04 08:59
OK, I've retried using 16.04LTS and, although I have an occasional successful login it usually fails.

[lightdm.log](https://github.com/MirServer/egmde-snap/files/3358523/lightdm.log)
[seat0-greeter.log](https://github.com/MirServer/egmde-snap/files/3358524/seat0-greeter.log)

I don't remember seeing this before:
```
[+34.75s] DEBUG: settings-daemon.vala:78: Failed to acquire name org.gnome.SessionManager
[+34.75s] DEBUG: settings-daemon.vala:105: Failed to acquire name org.gnome.ScreenSaver
[+34.75s] DEBUG: unity-greeter.vala:135: Failed to acquire name com.canonical.Unity

** (unity-settings-daemon:12429): WARNING **: Name taken or bus went away - shutting down
```

**Comment by AlanGriffiths** [comment] 2019-07-04 11:58
On my (18.04 based) MATE install I don't see that, but...
### lightdm.log
```plain
[+612.95s] DEBUG: Greeter requests session egmde
[+612.95s] DEBUG: Seat seat0: Creating display server of type wayland
[+612.95s] DEBUG: Using VT 7
[+612.95s] DEBUG: Launching process 28995: /sbin/prime-offload
[+612.95s] DEBUG: Process 28995 exited with return value 0
[+612.95s] DEBUG: Seat seat0: Exit status of /sbin/prime-offload: 0
[+612.95s] DEBUG: Seat seat0: Display server ready, running session
[+612.95s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session1
[+612.96s] DEBUG: Session pid=28804: Running command /usr/sbin/lightdm-session egmde
[+612.96s] DEBUG: Creating shared data directory /var/lib/lightdm-data/alan
[+612.96s] DEBUG: Session pid=28804: Logging to .xsession-errors
[+613.02s] DEBUG: Activating VT 7
[+613.25s] DEBUG: Seat seat0: Stopping greeter
[+613.25s] DEBUG: Terminating login1 session c2
[+613.26s] DEBUG: Session pid=28725: Sending SIGTERM
[+613.26s] DEBUG: Activating login1 session c3
[+613.26s] DEBUG: Session pid=28725: Exited with return value 0
[+613.26s] DEBUG: Seat seat0: Session stopped
[+613.26s] DEBUG: Seat seat0: Stopping display server, no sessions require it
[+613.26s] DEBUG: Sending signal 15 to process 28705
[+613.26s] DEBUG: Session pid=28804: Exited with return value 1
[+613.26s] DEBUG: Seat seat0: Session stopped
[+613.26s] DEBUG: Seat seat0: Stopping display server, no sessions require it
[+613.26s] DEBUG: Seat seat0: Display server stopped
[+613.26s] DEBUG: Launching process 29102: /sbin/prime-switch
[+613.36s] DEBUG: Process 29102 exited with return value 0
[+613.36s] DEBUG: Seat seat0: Exit status of /sbin/prime-switch: 0
[+613.36s] DEBUG: Seat seat0: Active display server stopped, starting greeter
[+613.36s] DEBUG: Seat seat0: Creating greeter session
[+613.36s] DEBUG: Seat seat0: Creating display server of type x
[+613.36s] DEBUG: Using VT 9
[+613.36s] DEBUG: Seat seat0: Starting local X display on VT 9
[+613.36s] DEBUG: XServer 1: Logging to /var/log/lightdm/x-1.log
[+613.36s] DEBUG: XServer 1: Writing X server authority to /var/run/lightdm/root/:1
[+613.36s] DEBUG: XServer 1: Launching X Server
```
### seat0-greeter.log
```plain
[+14.34s] DEBUG: Starting session egmde
[+14.34s] DEBUG: Wrote 17 bytes to daemon
[+14.65s] DEBUG: Read 8 bytes from daemon
[+14.65s] DEBUG: Read 4 bytes from daemon
[+14.65s] DEBUG: slick-greeter.vala:690: Got a SIGTERM
[+14.65s] WARNING: Error getting UserName from org.freedesktop.DisplayManager.Session: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/DisplayManager/Session1
Gdk-Message: 12:47:03.145: slick-greeter: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

**Comment by AlanGriffiths** [comment] 2019-07-18 16:25
@robert-ancell I've been testing with a fresh 16.04 install, and find it consistently logs in the first time following a reboot and consistently fails subsequently. Here are the logs:
[first-lightdm.log](https://github.com/MirServer/egmde-snap/files/3407446/first-lightdm.log)
[first-seat0-greeter.log](https://github.com/MirServer/egmde-snap/files/3407447/first-seat0-greeter.log)
[second-lightdm.log](https://github.com/MirServer/egmde-snap/files/3407448/second-lightdm.log)
[second-seat0-greeter.log](https://github.com/MirServer/egmde-snap/files/3407449/second-seat0-greeter.log)
There are some obvious differences in the seat0-greeter.logs but, unfortunately, nothing that's meaningful to me. Any suggestions?

**Comment by robert-ancell** [comment] 2019-07-29 16:25
Looks like the issue is this:
```
[+200.44s] DEBUG: Activating VT 8
[+200.63s] WARNING: Error using VT_WAITACTIVE 8 on /dev/tty0: Interrupted system call
```
Which was [fixed in LightDM 1.22](https://github.com/CanonicalLtd/lightdm/commit/6b1811323b6dbe5ffb30122ea90ba3b5df9fa617). I've [cherry picked this to 1.18](https://github.com/CanonicalLtd/lightdm/commit/e5e9b048f5336e76c31dbf1cd25298c0b292891a) in case you want to try it.

**Comment by AlanGriffiths** [comment] 2019-08-07 10:32
> Which was [fixed in LightDM 1.22](https://github.com/CanonicalLtd/lightdm/commit/6b1811323b6dbe5ffb30122ea90ba3b5df9fa617). I've [cherry picked this to 1.18](https://github.com/CanonicalLtd/lightdm/commit/e5e9b048f5336e76c31dbf1cd25298c0b292891a) in case you want to try it.

I tried it: It works.

Thanks @robert-ancell glad to have an explanation (of sorts).

**Comment by robert-ancell** [comment] 2019-08-07 22:52
@AlanGriffiths if you prepare an SRU I'd be happy to review/sponsor it if 16.04 LTS is important to support.

**Comment by AlanGriffiths** [comment] 2019-08-08 08:40
> @AlanGriffiths if you prepare an SRU I'd be happy to review/sponsor it if 16.04 LTS is important to support.

Thanks, but understanding where the problem lies is enough. Will revisit if it becomes an issue.

**Closed as not planned** 2023-05-03 09:26 UTC
Labels: wontfix
